version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app/src
    command: python app.py
    ports:
      - "15000:5000"
    networks:
      - library-network
    depends_on: 
      - db

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
    networks:
      - library-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  library-network:
